[project]
name = "extremeXP - Experiment Cards"
version = "0.1.0"
description = "The implementation of experiment cards module of ExtremeXP framework"

readme = "README.md"
requires-python = ">=3.10"

[project.dependencies]
dependencies = "requirements.txt"

